// GENERATED by agents/src/export-demo.ts — do not edit by hand.
// Run `npm run export-demo` in agents/ to regenerate. This is the agent engine's own
// 12-week replay output; the web "Demo" mode binds to it so nothing on screen is hand-typed.

export interface DemoAgentRow {
  rank: number;
  name: string;
  strategy: string;
  capital: number;
  votingPowerPct: number;
  accuracy: number;
  kind: "Agent";
}

/** Final standings after the 12-week replay — the headline leaderboard. */
export const LEADERBOARD: DemoAgentRow[] = [
  {
    "rank": 1,
    "name": "SectorBot",
    "strategy": "Sector Rotation",
    "capital": 2000,
    "votingPowerPct": 23.9,
    "accuracy": 3.3,
    "kind": "Agent"
  },
  {
    "rank": 2,
    "name": "ContrarianBot",
    "strategy": "Contrarian",
    "capital": 10000,
    "votingPowerPct": 19.2,
    "accuracy": -0.2,
    "kind": "Agent"
  },
  {
    "rank": 3,
    "name": "MeanRevBot",
    "strategy": "Mean Reversion",
    "capital": 4000,
    "votingPowerPct": 15.5,
    "accuracy": 1.3,
    "kind": "Agent"
  },
  {
    "rank": 4,
    "name": "ValueBot",
    "strategy": "Deep Value",
    "capital": 3000,
    "votingPowerPct": 15.2,
    "accuracy": 1.6,
    "kind": "Agent"
  },
  {
    "rank": 5,
    "name": "MomentumBot",
    "strategy": "Momentum Trend",
    "capital": 1000,
    "votingPowerPct": 14.2,
    "accuracy": 2,
    "kind": "Agent"
  },
  {
    "rank": 6,
    "name": "LowVolBot",
    "strategy": "Low Volatility",
    "capital": 6000,
    "votingPowerPct": 11.9,
    "accuracy": 0.1,
    "kind": "Agent"
  }
];

/** The demo cycle the user's vote+resolve plays out (matches the displayed cycle #). */
export const DEMO_CYCLE_ID = 4;

/** Real weekly return per ticker for the demo cycle (fraction, e.g. 0.073 = +7.3%). */
export const DEMO_CYCLE_RETURNS: Record<string, number> = {
  "AAPL": 0.0214,
  "NVDA": 0.0507,
  "MSFT": 0.0122,
  "AMZN": 0.0465,
  "GOOGL": 0.0199,
  "META": 0.0537,
  "TSLA": 0.0252,
  "JPM": 0.0116
};

/** S&P weekly return for the demo cycle — the benchmark accuracy is measured against. */
export const DEMO_SPX_RETURN = 0.0137;

/** Agent members (capital + final accuracy) — used to compute the user's voting-power share. */
export const AGENT_MEMBERS: { capital: number; accuracy: number; cycles: number }[] = [
  {
    "capital": 10000,
    "accuracy": -0.0023,
    "cycles": 12
  },
  {
    "capital": 6000,
    "accuracy": 0.0006,
    "cycles": 12
  },
  {
    "capital": 4000,
    "accuracy": 0.0128,
    "cycles": 12
  },
  {
    "capital": 3000,
    "accuracy": 0.0155,
    "cycles": 12
  },
  {
    "capital": 2000,
    "accuracy": 0.0329,
    "cycles": 12
  },
  {
    "capital": 1000,
    "accuracy": 0.0202,
    "cycles": 12
  }
];
