/**
 * Export the demo dataset the web app's mock mode renders (ROADMAP workstream E).
 *
 * Compute-only mirror of seed.ts: runs the 6 agents through the 12-week replay, then writes
 * the final leaderboard + the demo cycle's real returns to web/src/lib/demoData.ts. The web
 * "Demo" mode binds to this file, so nothing on screen is hand-typed — it's the agent engine's
 * own output (small-skilled agent out-ranks big-mediocre one) plus the same accuracy math the
 * user's own vote is scored against on resolve.
 *
 *   npm run export-demo
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { AGENTS } from "./agents.js";
import { STRATEGIES, type StrategyId } from "./strategies.js";
import { WEEKS, weekReturn } from "./fixture.js";
import { cycleAccuracy, ewma, votingPower } from "./resolve.js";
import { TICKERS, SPX } from "./universe.js";

// The cycle the user's live vote+resolve plays out — matches the displayed cycle #.
// Week 4 is broad-up across the universe, so the default tech-tilted basket posts a clear positive.
const DEMO_CYCLE = 4;

// Human-readable strategy labels for the leaderboard UI.
const STRATEGY_LABEL: Record<StrategyId, string> = {
  momentum: "Momentum Trend",
  value: "Deep Value",
  "mean-reversion": "Mean Reversion",
  sector: "Sector Rotation",
  "low-vol": "Low Volatility",
  contrarian: "Contrarian",
};

const round = (x: number, p = 2) => Number(x.toFixed(p));

// 12-week replay, compute only (no printing / no thesis) — same strategy + scoring as seed.ts.
// We capture the standings AFTER EACH cycle so the web can play the leaderboard as a race:
// early on, confidence is low so capital leads (ContrarianBot $10k on top); as accuracy
// accumulates and confidence ramps, the small-skilled SectorBot ($2k) climbs past it.
const acc: Record<string, number> = Object.fromEntries(AGENTS.map((a) => [a.id, 0]));
const frames: ReturnType<typeof standings>[] = [];

function standings(cycle: number) {
  return votingPower(
    AGENTS.map((a) => ({ id: a.id, capital: a.deposit, accuracy: acc[a.id]!, cycles: cycle })),
  )
    .sort((a, b) => b.votingPower - a.votingPower)
    .map((r, i) => {
      const agent = AGENTS.find((a) => a.id === r.id)!;
      return {
        rank: i + 1,
        name: agent.name,
        strategy: STRATEGY_LABEL[agent.strategy],
        capital: agent.deposit,
        votingPowerPct: round(r.votingPower * 100, 1),
        accuracy: round(r.accuracy * 100, 1),
        kind: "Agent" as const,
      };
    });
}

for (let cycle = 1; cycle <= WEEKS; cycle++) {
  for (const agent of AGENTS) {
    const pick = STRATEGIES[agent.strategy](cycle);
    acc[agent.id] = ewma(acc[agent.id]!, cycleAccuracy(pick.allocations, cycle));
  }
  frames.push(standings(cycle));
}

const leaderboard = frames[frames.length - 1]!; // final standings

// The demo cycle's real weekly returns — the web scores the user's own vote against these
// (same excess-vs-S&P formula as resolve.ts) and moves prices by the same amounts.
const returns: Record<string, number> = {};
for (const t of TICKERS) returns[t] = round(weekReturn(t, DEMO_CYCLE), 4);
const spxReturn = round(weekReturn(SPX, DEMO_CYCLE), 4);

// Peers for computing the user's voting power relative to the agents (votingPower in resolve.ts).
const members = AGENTS.map((a) => ({ capital: a.deposit, accuracy: round(acc[a.id]!, 4), cycles: WEEKS }));

const out = `// GENERATED by agents/src/export-demo.ts — do not edit by hand.
// Run \`npm run export-demo\` in agents/ to regenerate. This is the agent engine's own
// 12-week replay output; the web "Demo" mode binds to it so nothing on screen is hand-typed.

export interface DemoAgentRow {
  rank: number;
  name: string;
  strategy: string;
  capital: number;
  votingPowerPct: number;
  accuracy: number;
  kind: "Agent";
}

/** Final standings after the 12-week replay — the headline leaderboard. */
export const LEADERBOARD: DemoAgentRow[] = ${JSON.stringify(leaderboard, null, 2)};

/** Standings after each cycle (1..12) — the web plays these as a leaderboard race. */
export const LEADERBOARD_FRAMES: DemoAgentRow[][] = ${JSON.stringify(frames)};

/** The demo cycle the user's vote+resolve plays out (matches the displayed cycle #). */
export const DEMO_CYCLE_ID = ${DEMO_CYCLE};

/** Real weekly return per ticker for the demo cycle (fraction, e.g. 0.073 = +7.3%). */
export const DEMO_CYCLE_RETURNS: Record<string, number> = ${JSON.stringify(returns, null, 2)};

/** S&P weekly return for the demo cycle — the benchmark accuracy is measured against. */
export const DEMO_SPX_RETURN = ${spxReturn};

/** Agent members (capital + final accuracy) — used to compute the user's voting-power share. */
export const AGENT_MEMBERS: { capital: number; accuracy: number; cycles: number }[] = ${JSON.stringify(members, null, 2)};
`;

const dest = resolve(dirname(fileURLToPath(import.meta.url)), "../../web/src/lib/demoData.ts");
writeFileSync(dest, out);
console.log(`✓ wrote ${dest}`);
console.log(`  ${leaderboard.length} agents · top: ${leaderboard[0]!.name} (${leaderboard[0]!.votingPowerPct}% VP, ${leaderboard[0]!.accuracy}% acc)`);
